# Generated by Django 5.0.6 on 2024-06-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='timeEnd',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='timeStart',
            field=models.TimeField(null=True),
        ),
    ]
